# Generated by Django 3.0.3 on 2020-02-18 19:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('entity_type', models.CharField(choices=[('individual', 'Individual'), ('company', 'Company'), ('government', 'Government')], default='company', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_type', models.CharField(choices=[('employment', 'Employment'), ('sales', 'Sales'), ('LOI', 'Letter of intent'), ('NDA', 'Non-disclosure agreement'), ('partnership', 'Partnership'), ('other', 'Other')], max_length=200)),
                ('description', models.CharField(max_length=255)),
                ('valid_from', models.DateField(blank=True)),
                ('expires', models.DateField(blank=True)),
                ('status', models.CharField(blank=True, choices=[('negotiation', 'Negotiation'), ('active', 'Active'), ('cancelled', 'Cancelled'), ('terminated', 'Terminated'), ('expired', 'Expired')], max_length=20)),
                ('contract_party', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='deals.Partner')),
            ],
        ),
    ]
