# Generated by Django 3.0.3 on 2020-02-23 06:35

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='contract_number',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AddField(
            model_name='contract',
            name='foreign_contract_number',
            field=models.CharField(default='N/A', max_length=200),
        ),
    ]
