# Generated by Django 3.0.3 on 2020-02-24 22:17

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0006_partner_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='accepting_members',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='orgsecret',
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
