# Generated by Django 3.0.3 on 2020-03-06 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0007_auto_20200224_2217'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='document_link',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
    ]
