# Generated by Django 3.0.3 on 2020-06-11 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0008_contract_document_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='orgnr',
            field=models.CharField(blank=True, max_length=9),
        ),
        migrations.AddField(
            model_name='organization',
            name='trial',
            field=models.BooleanField(default=True),
        ),
    ]
