# Generated by Django 3.0.3 on 2020-06-12 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0010_auto_20200612_1044'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contract',
            name='notes',
        ),
    ]
