# Generated by Django 3.0.3 on 2020-06-12 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0011_remove_contract_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='owner',
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
