# Generated by Django 3.0.3 on 2020-06-14 20:01

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0013_contract_notes'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contract',
            options={'verbose_name': ('contract',), 'verbose_name_plural': 'contracts'},
        ),
        migrations.AlterField(
            model_name='contract',
            name='contract_number',
            field=models.UUIDField(default=uuid.uuid4, editable=False, verbose_name='contract_number'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='contract_party',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='deals.Partner', verbose_name='contract party'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='contract_type',
            field=models.CharField(choices=[('employment', 'Employment'), ('sales', 'Sales'), ('LOI', 'Letter of intent'), ('NDA', 'Non-disclosure agreement'), ('partnership', 'Partnership'), ('DPA', 'Data Protection Agreement'), ('other', 'Other')], max_length=200, verbose_name='contract_type'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='description',
            field=models.CharField(max_length=255, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='document_link',
            field=models.URLField(blank=True, max_length=255, null=True, verbose_name='document_link'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='expires',
            field=models.DateField(blank=True, null=True, verbose_name='expires'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='notes',
            field=models.TextField(blank=True, verbose_name='notes'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='owner',
            field=models.CharField(blank=True, max_length=128, verbose_name='owner'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='status',
            field=models.CharField(blank=True, choices=[('negotiation', 'Negotiation'), ('active', 'Active'), ('cancelled', 'Cancelled'), ('terminated', 'Terminated'), ('expired', 'Expired')], max_length=20, verbose_name='status'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='valid_from',
            field=models.DateField(blank=True, null=True, verbose_name='valid_from'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='entity_type',
            field=models.CharField(choices=[('individual', 'Individual'), ('company', 'Company'), ('government', 'Government')], default='company', max_length=255, verbose_name='entity_type'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='name',
            field=models.CharField(max_length=255, verbose_name='name'),
        ),
    ]
